### ISSUE TITLE
Top-level CBE package

### ISSUE THREAD

**Issue by nfeske** [cbe-project/cbe#2]
All CBE code resides in a  top-level package and sub packages. Style-wise should the package name be `Cbe` or `CBE`? The top-level package should contain only a few basic types and values used within our CBE universe and for the ABI (where C++ would interface with SPARK).

* Block size
  
  I propose to define the `Block_Size` to the fixed value `4096`. All sub packages should refer to `Block_Size`. By defining the value in top-level CBE package, we can easily change it later on. However, it won't be possible to have one program that handles a variety of block sizes. If we wanted to support that, the CBE top-level package would need to be a generic. I my opinion, this presumed flexibility is not needed. So I would like to stick to one global definition of the value.

* Block number: expresses a logical block number in the unit of blocks as a 64-bit unsigned integer.
  
  I wonder, would it be sensible to model the distinction between logical blocks and physical blocks by two different types?

* Block offset: a 64-bit unsigned integer value that denotes the position of payload in the outside communication buffer. It is opaque to the SPARK code.

* Block operation enum with the values READ, WRITE, SYNC.

**Comment by m-stein** [comment]
For me, looking just at the CBE-internal world, it makes sense to have a distinction between front-end and back-end block number. With it, we can exclude mix-ups of such values when debugging and if, eventually, it should turn out to be not as sensible as hoped, it can be removed easily. I would even leave out the valuation as logical and physical adresses as especially the latter might not be true and therefore misleading.

**Comment by nfeske** [comment]
I'm wondering, doesn't "front-end block number" correspond to "logical block number", and "back-end block number" to "physical block number"? Just different names.

I would rather speak of "physical" and "logical" instead of "back-end" and "front-end".

Please consider that the notion of back/front end may be overloaded inside an individual module. E.g., think of the cache. The cache only cares for physical block numbers. But it has a front end (the user that requests content from the cache) and a back end (that consumes requests generated by the cache). Calling the physical block numbers "back-end block numbers" would be quite confusing.

**Comment by senier** [comment]
We try to follow the [Ada Style guide](https://en.wikibooks.org/wiki/Ada_Style_Guide) regarding coding style. Abbreviations like CBE (though discouraged) are upper case.

I agree that we should have a toplevel package `CBE`. I would not put the types into that root package, though. We usually have some additional package `<Project>.Types` for that. An important reason is that  the private part and body of all child packages have visibility to the private part of their parent package. In other words, all packages can access the private types definition in the root package.

The block size should indeed be a constant. Instead of defining is in the parent package I'd rather have another child package (`CBE.Options`) that only contains such rather static compiler-time parameters. The benefit is that we could build with different parameters by providing different `cbe-options.ads` files. Replacing the root package may break things (depending on what else is in there).

Differentiating logical and physical may indeed save us some headaches. Using 64bit unsigned integers may be a problem, though. In Ada, unsigned integers are required to be a subtype of a symmetric signed integer. This implies that you need a native 65 bit integer type to represent a true 64bit unsigned number. An alternative is a 64bit modular type, but this has wraparound semantics and the drawbacks mentioned in #1. Would a 63bit unsigned integer (based on a 64bit signed) be an option (so we only have 63bit block addresses)?

I'm not sure I understand the block offset - which outside communication buffer are you referring to?

Regarding enums we need to decide how to model the SPARK side. C++ enums can be realized as Ada enumerations (that's what we do in the binding generator), but this has the drawback that variables of that enum type can become invalid (i.e. contain a value that does not correspond to one of the enum elements). Unfortunately, SPARK does not consider that problem right now (to my knowledge) and you may get Exceptions at runtime then.

Another option is a (dedicated) numeric type and respective constants. This, however, takes away the opportunity to check completeness (e.g. in case statements). In RecordFlux we use a combination of both - external data is represented by an integer type and we generate a function that maps between this and a an enum type (which is never initialized by untrusted data). For READ/WRITE/SYNC we can write to simple expression functions that do that (the enum needs an "INVALID" element in this case).

**Comment by nfeske** [comment]
I like your suggestions, @senier!

The types I was speaking about in my initial text referred to the ABI level - the underlying representation at the boundary of C++ and SPARK. On the SPARK side these ABI types may live under `CBE.Cxx`. Within the actual CBE code, we can (and should) use stricter types that are most suitable for the verification. In particular, there is no need to model the `Block_number` as a modular type. `CBE.Types.Block_Number` should be natural number with a range that is adequate for the domain. 64 bit wouldn't be needed here. The same goes for the enum question. `CBE.Cxx.Types.Operation` can be a numeric type + a bunch of constants, whereas `CBE.Types.Operation` would be a SPARK enum. The conversion functions between those types would be in charge of satisfying the constraints of the strict types (like the ranges).

> I'm not sure I understand the block offset - which outside communication buffer are you referring to?

I appreciate your scrutiny. The role of this value actually corresponds tho the `Request_Tag`. It ought to be used to differentiate multiple client requests that are currently in flight. Within the existing block-services of Genode, we use the data offset within the packet stream as such a tag. But this implementation detail should better not spill over to the CBE. Let's better talk about a `Request_Tag`. Good point.

**Comment by m-stein** [comment]
The translation module is now translated to SPARK and works (my cbe_sparkify_translation_module branch, based on the last working state of cnuke/cbe_wip). Note, that I had to adapt the LSC-SHA256-4K to be pure which isn't upstream yet.

**Comment by m-stein** [comment]
@nfeske The top-level package named CBE is part of the current master and contains the discussed types. That said, may I ask you to close this issue?
