### ISSUE TITLE
Get rid of address overlays

### ISSUE THREAD

**Issue by m-stein** [cbe-project/cbe#25]
Code like this
```
A : A_Type;
B : B_Type with Address => A'Address;
```
is often used in the current state of the CBE library to do an unconditional cast between two types. This not only violates type safety but also makes flow analysis with gnatprove a mine field (not to speak of stronger proving modes that of course wouldn't be possible at all). The existence of or assignments to a local variable etc. are considered unnecessary although they are not because. The connection between the cast operands is not taken into account.

Therefore, such constructs should be replaced by explicit type conversions with thorough checking.

**Comment by m-stein** [comment]
This is a sketch of one way to convert between raw data blocks and structured types:

f4d4176 SKETCH cbe: get rid of address overlays

It has the disadvantage compared to address overlays that it needs to copy the whole block twice when we want to modify data in place and that the conversion code is pretty bloated. The latter could, however, be mitigated by using a bigger integer type in ``Block_Data_Type``. When doing so, I assume a 32 bit unsigned integer would be preferable over a 64 bit one as it could be expressed without ``mod``!?

The same would have to be done for the conversion between the different raw block data types (CBE, SHA256, Hash) as they are unfortunately not compatible with each other (item type differs although it's de-facto the same).

**Comment by m-stein** [comment]
Any opinions or advice on that?

**Comment by jklmnn** [comment]
There are two different scenarios: payload data and data we have to handle.

For the payload data type safety is only relevant in that plain and cipher text should never mix. We do not care about the internal structure or representation of the data. Another problem is that we usually have large chunks of payload data and that we have many chunks. As a result the unchecked conversion with `Ada.Unchecked_Conversion` is undesirable since it copies the (probably large chunk) on the stack. Also converting the type byte-wise might be a performance bottleneck (depending on the actual compiler optimizations), especially since we have to do often.
We usually use two methods to circumvent those problems:
 - generic packages: The payload data type is made a generic parameter. As it doesn't need to be used internally. So anything can be a payload as long as it holds certain properties (e.g. an array of 8bit values).
 - address overlay wrapper: If generics cannot be employed, we resort to a wrapper around the address overlay. The wrapper even might be `SPARK_Mode => Off`. It is a procedure with an `in` and an `out` parameter of the regarding types (this wrapper can be generic again). It keeps the data flow correct to some extent (as it looks like an assignment) but of course you loose all assumptions of the `in` parameter. One could even provide a contract to create a correlation between the `in` and the `out` parameter but this cannot be checked by SPARK and therefore has to be correct.

The meta data (aka data we have to handle) has (to my understanding) different properties (assuming we're talking about blocks of meta data saved on the disk). We have to know its structure so we cannot simply make it generic. But there are far less objects than there are of payload data. Essentially it can be treated as a package of a specific protocol we need to parse. So this leaves two options:
 - address overlay wrapper: The address overlay wrapper as explained before can be used here, too. Although we have to check the contents of the output type for its validility. This only works for fixed size chunks (which is the case here, I think). Yet again it might loose some properties between the input and the output.
 - manually parsing from the source type (afaict this is what you did): This has the advantage that it is clear to SPARK what is happening here. Also this makes it possible to detect malformed input quite early. Yet it requires more work. For the sake of soundness I'd prefer this version. And I think the performance overhead is negligible since all fields have to be checked in the first approach, too.

In general it's hard to make any safe assumption about the performance penalties of any of these approaches without testing them as it depends highly on what the compiler is actually doing.

**Comment by m-stein** [comment]
Fixed on my cbe/merge_to_staging branch.

@jklmnn Thanks for the very detailed explanation on this topic. For now, I have implemented the most pedantic approach of always translating byte by byte (copying). I would leave optimizations for later as it is not on a critical path right now. What do you say?

**Comment by senier** [comment]
@m-stein Note, that most libsparkcrypto functions [are generic these days](https://github.com/Componolit/libsparkcrypto/blob/componolit/src/shared/generic/lsc-sha2_generic.ads) - this should make explicit conversions unnecessary.

**Comment by m-stein** [comment]
@senier Thanks for the hint! This should indeed make some conversions unnecessary.

**Comment by m-stein** [comment]
This issue is fixed on current master.
