### ISSUE TITLE
Request-pool module

### ISSUE THREAD

**Issue by cnuke** [cbe-project/cbe#5]
The request-pool module stores a client request with a corresponding tag. The tag is passed to the splitter module (together with the request) and is used to _tag_ the resulting primitives.

It implements the following interface:

**`request_acceptable`** returns true if the request can be added to the pool.

**`submit_request`** adds the given client request to the pool.

**`peek_pending_request`** returns true if the pool contains a pending request.

**`take_pending_request`** returns the next pending request and marks it as _in progress_.

**`set_primitive_count`** sets the number of primitives belonging to the given tag. _Alternatively the number of primitives could instead be an argument for `submit_request`._

**`mark_completed_primitive`** marks the given primitive as completed. If all primitives belonging to a request are complete, the request is marked as _complete_.

**`peek_completed_request`** returns true if the pool contains a completed request.

**`take_completed_request`** returns the completed request, i.e. all primitives are marked as done, and removes the request from the pool.

**Comment by nfeske** [comment]
Thanks for the write-up.

> Alternatively the number of primitives could instead be an argument for `submit_request`.

I think that's a good idea. This way, the submission of a request is an atomic operation and the number of primitives can be a `const` member of the resource-pool element.

**Comment by cnuke** [comment]
Yeah, I actually made this change yesterday because it did not feel right to call **`splitter.number_of_primitives`** with the current request before storing the request. After all the splitter module is not needed strictly needed for the request-pool module to accept a request. But then again, having the non atomic operation bothered me as well (hence mentioning the alternative way and previous implementation).

**Comment by senier** [comment]
I second the idea to pass the number of primitives in `submit_request`. The request pool interfaces looks good to me.

**Comment by m-stein** [comment]
One small side note (@cnuke) while I'm translating the request pool to SPARK:
Maybe we should not use tags (or other object identifiers) as index for an array (e.g., a buffer of objects). I will instead iterate over the array and compare the tags to find the correct object. This way, a tag can be anything and changes to the tag type wont break the modules. What do you think?

**Comment by cnuke** [comment]
I don't mind you changing the way you address an entry for a given tag within the module. After all that's just an implementation detail. That being said, the tag is just an opaque type for all other modules besides the request_pool (at least for now) and it stands to reason if need to put more meaning into or if other modules may rely on its value.

**Comment by m-stein** [comment]
The ``spark_cbe`` component on my [CBE branch](https://github.com/m-stein/genode/commits/cbe) was now reworked according to the latest off-line discussion regarding ``tag`` as member of ``Block::Request``. I didn't use the offset as tag as suggested earlier because different requests may legally have the same offset. I also applied that the ``CBE.Pool`` takes and returns requests only and therefore the former public ``CBE.Pool_Primitive`` type can be replaced by an ``Item`` type private to ``CBE.Pool``.

I will incorporate variant records again later, as soon as the glue code for ``CBE.Pool`` works.

**Comment by cnuke** [comment]
It would be nice if you could briefly describe why adding the `tag` as member is necessary and why it is needed for non-CBE related block components (I imagine it could be used as some kind of cookie to make handling of outstanding requests easier at the client side?).

**Comment by m-stein** [comment]
These two statements combined require ``tag`` to be a member of ``Request``:
* The ``tag`` shall be accessible to the world outside of the request-pool module, so, other modules can stick it to primitives they create in the context of processing the corresponding request.
* At the other hand, the request pool shall hand out only ``Request`` objects to the outer world. 

Furthermore:
* The ``tag`` cannot be replaced by any combination of the existing members of ``Request`` as we cannot expect their values to be unique.
* The ``tag`` cannot be replaced by the address of the ``Request`` object neither as the objects are copyable and actually copied quite a lot.

I think the point of tag allocation, however, would be better located inside the request pool. I moved it to the CBE top level because there the existing bit allocator can be used (yet).

**Comment by cnuke** [comment]
Right, thanks for the explanation.

**Comment by m-stein** [comment]
Of course, handing around the tag separately, we would not force each block component to hand it around (e.g. drivers might not be interested in it at all). Also, the value of the tag member is not sensible by default. Currently, I set it to zero initially as I didn't want to add a tag allocator to the request stream. This is error-prone as the developer is pretty free in deciding when to set it valid and when to reset it to an invalid value.

**Comment by nfeske** [comment]
As another consideration, we should keep in mind that the CBE also requires a few tags for itself. In particular the primitives generated by the TLB must be tagged especially so that they are not wrongly associated with client requests.

The thought actually undermines my intuition to use the request offset as tag value.

**Comment by m-stein** [comment]
On my Genode -> CBE branch I have now integrated the SPARK request-pool module and it works. However, again the test causes loads of warnings (w/o variant records) with the recent commit:
```
[init -> spark_cbe] Warning: Get_Jmpbuf_Address_Soft not implemented
[init -> spark_cbe] Warning: Set_Jmpbuf_Address_Soft not implemented
[init -> spark_cbe] Warning: Set_Jmpbuf_Address_Soft not implemented
```
And I have not found the reason for this yet.
